### ISSUE TITLE
Error when running any command with a positional argument

### ISSUE THREAD

**Issue by jochakovsky** [huntcsg/bragly#8]
```
$ brag s
No configuration found, using default configuration: 
Traceback (most recent call last):
  File "/usr/local/bin/brag", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/bragly/__main__.py", line 36, in main
    for result in results:
  File "/usr/local/lib/python2.7/site-packages/bragly/brag.py", line 92, in search
    for result in results:
  File "/usr/local/lib/python2.7/site-packages/bragly/persist.py", line 77, in search
    mech, config = _get_module_and_kwargs_from_config(mechanism)
  File "/usr/local/lib/python2.7/site-packages/bragly/persist.py", line 93, in _get_module_and_kwargs_from_config
    config = get_config(mechanism)
  File "/usr/local/lib/python2.7/site-packages/bragly/config.py", line 49, in get_config
    if 'mechanism' in conf_parser:
TypeError: argument of type 'instance' is not iterable
```

**Comment by huntcsg** [comment]
This is due to python 2.7 compatibility. I need to update some of the calls, and make sure that  test coverage improves to catch regression.

**Comment by huntcsg** [comment]
This has been fixed. Please install the latest version with pip.

```
$ pip uninstall bragly
$ pip install bragly --no-cache-dir
```
